import { BRAND } from '../config';

export default {
  lang: 'en',
  dir: 'ltr',
  meta: {
    title: `${BRAND.name} — Maison de Parfum`,
    description: `${BRAND.name} is a fictional perfume house. Built by ${BRAND.studio}.`,
  },
  nav: {
    story: 'Story', notes: 'Notes', shop: 'Shop', bag: 'Bag', menu: 'Menu', close: 'Close',
    toggle: 'ع', toggleLabel: 'العربية', home: `${BRAND.name}, back to the sky`,
  },
  loader: { label: 'Loading' },
  hero: {
    eyebrow: 'Maison de Parfum',
    word: BRAND.name,
    tagline: 'Scent, remembered.',
    cta: 'Begin the journey',
    scroll: 'Scroll',
  },
  manifesto: {
    label: 'Manifesto',
    lines: [
      'Every scent begins far from the bottle —',
      'in a field at dawn, in a hand that picks it,',
      'in the patience of the ones who make it.',
    ],
  },
  origins: {
    label: 'Origins',
    chapters: [
      { key: 'land', name: 'The Land', title: 'Where the rose wakes', line: 'Highland fields, mist still in the valleys, the first light on the petals.', alt: 'Damask rose bushes in bloom across a highland field at first light' },
      { key: 'hand', name: 'The Hand', title: 'Picked before the sun', line: 'By hand, at dawn, while the scent is still held inside the petal.', alt: 'Freshly picked rose petals spilling from a woven basket' },
      { key: 'craft', name: 'The Craft', title: 'Drop by drop', line: 'Copper, steam and time — until a single drop of oil remains.', alt: 'A hammered copper alembic in warm light' },
      { key: 'time', name: 'The Time', title: 'Oud does not hurry', line: 'Resin that takes years to form, smoke that takes its time to rise.', alt: 'A thread of smoke curling slowly in the dark' },
    ],
  },
  notes: {
    label: 'Inside the fragrance',
    title: 'AZAL No. 1 — Rose & Oud',
    layers: [
      { n: '01', name: 'Top', notes: 'Bergamot, Pink Pepper, Saffron' },
      { n: '02', name: 'Heart', notes: 'Taif Rose, Jasmine' },
      { n: '03', name: 'Base', notes: 'Oud, Amber, White Musk' },
    ],
    buyLine: 'AZAL No. 1 — Rose & Oud · 50 ml',
  },
  collection: {
    label: 'The collection',
    title: 'One house, five characters.',
    discover: 'Discover', add: '+ Add', from: 'From', prev: 'Previous fragrance', next: 'Next fragrance',
    viewAll: 'View all fragrances',
  },
  finale: {
    top: 'Wear',
    bottom: 'what stays.',
    cta: 'Back to the sky',
  },
  footer: {
    note: `Built by ${BRAND.studio}`,
    shop: 'Shop', delivery: 'Delivery & returns', contact: 'Contact',
  },
  bottleAlt: `${BRAND.name} No. 1, a heavy arched glass bottle with rose-amber perfume, a gold printed mark and an ivory stone cap`,

  shop: {
    title: 'The fragrances',
    lead: 'Five eaux de parfum and a set to discover them.',
    filters: { all: 'All', floral: 'Floral', woody: 'Woody', amber: 'Amber', musk: 'Musk' },
    empty: 'Nothing in this family yet.',
    from: 'From',
    add: '+ Add',
  },
  product: {
    edp: 'Eau de Parfum',
    size: 'Size', quantity: 'Quantity', decrease: 'Decrease quantity', increase: 'Increase quantity',
    add: 'Add to bag', adding: 'Adding…', added: 'Added ✓',
    notes: 'Notes', top: 'Top', heart: 'Heart', base: 'Base',
    story: 'The story', wear: 'How to wear', delivery: 'Delivery & returns',
    deliveryText: 'This is a demo store: nothing is sold, shipped or charged. In a live store, standard delivery would take 2–4 days across Saudi Arabia, express next day in Riyadh, Jeddah and Dammam, with returns of unopened bottles within 14 days.',
    also: 'You may also like',
    back: 'All fragrances',
    notFound: 'This fragrance does not exist.',
  },
  cart: {
    title: 'Your bag',
    empty: 'Your bag is empty.',
    discover: 'Discover the collection',
    remove: 'Remove',
    gift: 'Add gift wrapping — complimentary',
    giftMsg: 'Gift message (optional)',
    giftPh: 'A few words for the card',
    subtotal: 'Subtotal',
    delivery: 'Delivery',
    deliveryLater: 'Calculated at checkout',
    total: 'Total',
    checkout: 'Checkout',
    continue: 'Continue shopping',
    close: 'Close bag',
    toast: 'Added to bag',
    view: 'View bag',
  },
  checkout: {
    title: 'Checkout',
    demo: 'Demo store — no payment is taken and no card details are collected.',
    back: 'Back to shop',
    contact: 'Contact', email: 'Email', phone: 'Phone', phoneHint: 'Saudi mobile: +966 5X XXX XXXX',
    deliveryH: 'Delivery', name: 'Full name', city: 'City', cityPh: 'Choose a city', district: 'District', street: 'Street',
    building: 'Building number', buildingHint: '4 digits, from the national address', notes: 'Delivery notes (optional)',
    method: 'Delivery method',
    standard: 'Standard', standardEta: '2–4 days',
    express: 'Express', expressEta: 'Next day · Riyadh, Jeddah, Dammam',
    expressNo: 'Express is only available in Riyadh, Jeddah and Dammam.',
    free: 'Free', freeOver: 'Free standard delivery over',
    payment: 'Payment', card: 'Card', mada: 'mada', apple: 'Apple Pay', tabby: 'Tabby — split in 4',
    payNote: 'Demo only. Selecting a method collects nothing.',
    place: 'Place order',
    placing: 'Placing order…',
    summary: 'Order summary', show: 'Show order summary', hide: 'Hide order summary', edit: 'Edit bag',
    giftLine: 'Gift wrapping', vat: 'Prices include VAT',
    emptyBag: 'Your bag is empty — there is nothing to check out yet.',
    errors: {
      email: 'Enter an email like name@example.com.',
      phone: 'Enter a Saudi mobile number, e.g. +966 55 123 4567.',
      name: 'Enter your full name.',
      city: 'Choose your city.',
      district: 'Enter your district.',
      street: 'Enter your street.',
      building: 'Enter the 4-digit building number.',
      summary: 'Please check the highlighted fields.',
    },
  },
  order: {
    thanks: 'Thank you',
    prepared: (id: string) => `Your order ${id} is being prepared.`,
    items: 'Items', deliverTo: 'Delivering to', method: 'Method',
    demo: 'Demo order — nothing was charged or will be shipped.',
    back: 'Back to the sky',
    missing: 'We could not find this order on this device.',
  },
  cities: ['Riyadh', 'Jeddah', 'Makkah', 'Madinah', 'Dammam', 'Khobar', 'Dhahran', 'Taif', 'Abha', 'Khamis Mushait', 'Tabuk', 'Buraidah', 'Hail', 'Jazan', 'Najran', 'Al Ahsa', 'Yanbu', 'Al Jubail'],
  cursor: { drag: 'Drag', view: 'View' },
};
